service: serverless-cqrs

frameworkVersion: "=1.25.0"
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  create:
    handler: posts.create
    events:
      - http:
          path: posts/create
          method: post
  command:
    handler: command.createCustomer
    events:
      - sns: command-createCustomer
